version: '3.8'

# Network
networks:
    inception:
        driver: bridge

# Volumes
volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: none
            device: /home/jaeshin/data/mysql
            o: bind

    wordpress:
        name: wordrpess
        driver: local
        driver_opts:
            type: none
            device: /home/jaeshin/data/wordpress
            o: bind

# Services
services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        restart: always
        ports:
            - 443:443
        networks:
            - inception
        depends_on:
            - wordpress
        env_file:
            - .env
        volumes: 
            - wordpress:/var/www/html/
        expose:
            - 443

    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: always
        ports:
            - 3306:3306
        networks:
            - inception
        env_file:
            - .env
        volumes: 
            - mariadb:/var/lib/mysql
        expose:
            - 3306
    
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        restart: always
        ports:
            - 9000:9000
        depends_on:
            - mariadb
        networks:
            - inception
        env_file:
            - .env
        volumes: 
            - wordpress:/var/www/html/
        expose:
            - 9000
